spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookmark
    username: alina
    password: p7%Ei@@).*9
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /bookmarkmanager
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-stacktrace: ON_PARAM
    include-exception: false